/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package subbvasalud.views;

import com.ezware.oxbow.swingbits.table.filter.TableRowFilterSupport;
import java.awt.event.ItemEvent;
import static java.awt.image.ImageObserver.WIDTH;
import java.io.File;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import subbvasalud.controllers.AnioController;
import subbvasalud.controllers.FarmaciaController;
import subbvasalud.controllers.PeriodoController;
import subbvasalud.models.Anio;
import subbvasalud.models.Periodo;
import subbvasalud.models.Socio;

/**
 *
 * @author damage
 */
public class ProgressDialogFarmacia extends javax.swing.JDialog {

    private static File file;
    public ProgressDialogFarmacia thisDialog;
    LinkedList<Socio> ls;
    Socio s;
    PeriodoController pc;
    Periodo p;
    AnioController ac;
    LinkedList<Anio> la;

    /**
     * Creates new form progressDialog
     *
     * @param parent
     * @param modal
     */
    public ProgressDialogFarmacia(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        ls = new LinkedList<>();
        pc = new PeriodoController();
        ac = new AnioController();
        p = new Periodo();
        s = new Socio();
        ls = s.getAllSocios();
        initComponents();
        TableRowFilterSupport.forTable(periodoTable).searchable(true).apply();
        anioComboBox.removeAllItems();
        la = ac.fillAnioComboBox(anioComboBox);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cargaPanel = new javax.swing.JPanel();
        anioLabel = new javax.swing.JLabel();
        anioComboBox = new javax.swing.JComboBox();
        saveButton = new javax.swing.JButton();
        selectPeriodoNewSolicitudLabel = new javax.swing.JLabel();
        periodoScrollPanel = new javax.swing.JScrollPane();
        periodoTable = new javax.swing.JTable();
        cargandoFarmacia = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Carga de socios");
        setFocusable(false);
        setLocationByPlatform(true);
        setModal(true);
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        cargaPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Cargar farmacias"));
        cargaPanel.setFocusable(false);

        anioLabel.setText("Año");

        anioComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                anioComboBoxItemStateChanged(evt);
            }
        });

        saveButton.setText("Ingresar Farmacias");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        selectPeriodoNewSolicitudLabel.setText("Periodo");

        periodoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Periodo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        periodoTable.setToolTipText("");
        periodoTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        periodoTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                periodoTableMouseClicked(evt);
            }
        });
        periodoScrollPanel.setViewportView(periodoTable);

        javax.swing.GroupLayout cargaPanelLayout = new javax.swing.GroupLayout(cargaPanel);
        cargaPanel.setLayout(cargaPanelLayout);
        cargaPanelLayout.setHorizontalGroup(
            cargaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cargaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cargaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectPeriodoNewSolicitudLabel)
                    .addComponent(anioLabel))
                .addGap(47, 47, 47)
                .addGroup(cargaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cargaPanelLayout.createSequentialGroup()
                        .addComponent(cargandoFarmacia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(saveButton))
                    .addGroup(cargaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(periodoScrollPanel)
                        .addGroup(cargaPanelLayout.createSequentialGroup()
                            .addComponent(anioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(500, 500, 500))))
                .addContainerGap())
        );
        cargaPanelLayout.setVerticalGroup(
            cargaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cargaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cargaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anioLabel))
                .addGap(18, 18, 18)
                .addGroup(cargaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(periodoScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectPeriodoNewSolicitudLabel))
                .addGap(18, 18, 18)
                .addGroup(cargaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cargandoFarmacia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cargaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cargaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus

    }//GEN-LAST:event_formWindowGainedFocus

    private void anioComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_anioComboBoxItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            int year = (int) anioComboBox.getSelectedItem();
            if (year != 0) {
                while (((DefaultTableModel) periodoTable.getModel()).getRowCount() != 0) {
                    ((DefaultTableModel) periodoTable.getModel()).removeRow(0);
                }
                pc.mostrarPeriodos((DefaultTableModel) periodoTable.getModel(), year);
            }
        }
    }//GEN-LAST:event_anioComboBoxItemStateChanged

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        int row = periodoTable.getSelectedRow();
        if (row != -1) {
            p = p.getPeriodoById((int) periodoTable.getModel().getValueAt(row, 0)); 
            Thread t = new Thread(new Runnable() {
                @Override
                public void run() {                    
                    FarmaciaController fc = new FarmaciaController();
                    cargandoFarmacia.setIndeterminate(true);
                    fc.ingresoFarmacias(file, thisDialog.p);
                    cargandoFarmacia.setIndeterminate(false);
                    thisDialog.dispose();
                }
            });
            t.start();

        } else {
            JOptionPane.showMessageDialog(this, "Seleccione el periodo de farmacia correctamente", "Periodo No seleccionado", WIDTH);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void periodoTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_periodoTableMouseClicked

    }//GEN-LAST:event_periodoTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[], File inputFile) {
        file = inputFile;
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProgressDialogFarmacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProgressDialogFarmacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProgressDialogFarmacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgressDialogFarmacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ProgressDialogFarmacia dialog = new ProgressDialogFarmacia(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {

                    }
                });
                dialog.thisDialog = dialog;
                dialog.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox anioComboBox;
    private javax.swing.JLabel anioLabel;
    private javax.swing.JPanel cargaPanel;
    private javax.swing.JProgressBar cargandoFarmacia;
    private javax.swing.JScrollPane periodoScrollPanel;
    private javax.swing.JTable periodoTable;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel selectPeriodoNewSolicitudLabel;
    // End of variables declaration//GEN-END:variables
}
